### ISSUE TITLE
[feat] GET - 글쓰기 뷰 상단 모임 주제 조회

### ISSUE THREAD

**Issue by sohyundoh** [Mile-Writings/Mile-Server#18]
## 📌  Feature Issue

List로 해당 모임에 해당하는 주제 list 반환하는 API 구현
<img width="813" alt="image" src="https://github.com/Mile-Writings/Mile-Server/assets/79795051/4d31cc76-9e92-4f8c-9c26-94de211684f9">

## 📝  To-do

- [x] 예외 사항 : 사용자 권한 체크, 존재하지 않은 모임일 경우
- [x] 로직 구현 및 테스트
- [x] Swagger 문서 작성
