### ISSUE TITLE
[feat] CD 플로우 설계 

### ISSUE THREAD

**Issue by sohyundoh** [Mile-Writings/Mile-Server#9]
## 📌  Feature Issue

- Dockerfile로 구성한 Spring Boot 서버 이미지를  Docker Hub 에 올려 실행시키는 방식의 CD 구축
## 📝  To-do

- [x] Health Check Actuator 의존성 추가
- [x] Dockerfile 작성
- [x] deploy.sh ec2에 추가
- [x] github secrets 추가
- [x] CD.yml 워크플로우 파일 작성
